[pytest]
pythonpath = 
    backend/etl
    backend
DJANGO_SETTINGS_MODULE = etl.settings
norecursedirs = env venv .git migrations __pycache__
addopts = -vv -s --failed-first
testpaths = backend/tests/
python_files = test_*.py
