# Generated by Django 6.0.2 on 2026-02-14 17:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['pk'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('source_type', models.CharField(choices=[('file', 'Файл'), ('database', 'База данных')], default='file', max_length=20, verbose_name='Тип источника')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обработка'), ('ready', 'Готов'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('original_file', models.FileField(blank=True, upload_to='uploads/originals/%Y/%m/', verbose_name='Оригинальный файл')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('sheet_name', models.CharField(blank=True, max_length=255, verbose_name='Лист (для XLSX)')),
                ('db_engine', models.CharField(blank=True, help_text='postgresql, mysql, …', max_length=50, verbose_name='Движок БД')),
                ('db_host', models.CharField(blank=True, max_length=255, verbose_name='Хост')),
                ('db_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порт')),
                ('db_name', models.CharField(blank=True, max_length=255, verbose_name='Имя БД')),
                ('db_user', models.CharField(blank=True, max_length=255, verbose_name='Пользователь')),
                ('db_password', models.CharField(blank=True, max_length=255, verbose_name='Пароль')),
                ('db_schema', models.CharField(blank=True, max_length=255, verbose_name='Схема')),
                ('db_table', models.CharField(blank=True, max_length=255, verbose_name='Таблица')),
                ('parquet_file', models.FileField(blank=True, upload_to='datasets/%Y/%m/', verbose_name='Parquet-файл')),
                ('row_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Число строк')),
                ('column_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Число столбцов')),
                ('columns_meta', models.JSONField(blank=True, default=list, help_text='[{"name": "col", "dtype": "int64"}, …]', verbose_name='Метаданные столбцов')),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Источник данных',
                'verbose_name_plural': 'источники данных',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Пайплайн',
                'verbose_name_plural': 'пайплайны',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('operation_type', models.CharField(choices=[('source_file', 'Загрузка из файла'), ('source_db', 'Загрузка из БД'), ('filter_rows', 'Фильтрация строк'), ('select_columns', 'Выбор столбцов'), ('rename_columns', 'Переименование столбцов'), ('sort', 'Сортировка'), ('join', 'Объединение таблиц (JOIN)'), ('aggregate', 'Агрегация'), ('cast_types', 'Приведение типов'), ('computed_column', 'Вычисляемый столбец'), ('split_column', 'Разделение столбца'), ('merge_columns', 'Слияние столбцов'), ('deduplicate', 'Удаление дубликатов'), ('fill_missing', 'Заполнение пропусков'), ('export_file', 'Экспорт в файл')], max_length=30, verbose_name='Тип операции')),
                ('label', models.CharField(help_text='Человекочитаемое имя узла для отображения на фронте.', max_length=100, verbose_name='Метка')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Параметры операции (зависят от operation_type).', verbose_name='Конфигурация')),
                ('position_x', models.FloatField(default=0, verbose_name='X')),
                ('position_y', models.FloatField(default=0, verbose_name='Y')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.pipeline', verbose_name='Пайплайн')),
            ],
            options={
                'verbose_name': 'Узел',
                'verbose_name_plural': 'узлы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('running', 'Выполняется'), ('success', 'Успех'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery Task ID')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.pipeline', verbose_name='Пайплайн')),
            ],
            options={
                'verbose_name': 'Запуск пайплайна',
                'verbose_name_plural': 'запуски пайплайна',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('running', 'Выполняется'), ('success', 'Успех'), ('failed', 'Ошибка'), ('skipped', 'Пропущен')], default='pending', max_length=20, verbose_name='Статус')),
                ('output_parquet', models.FileField(blank=True, upload_to='runs/outputs/%Y/%m/', verbose_name='Выходной Parquet')),
                ('output_row_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Число строк')),
                ('output_columns_meta', models.JSONField(blank=True, default=list, verbose_name='Метаданные столбцов')),
                ('logs', models.TextField(blank=True, verbose_name='Логи')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.node', verbose_name='Узел')),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='core.pipelinerun', verbose_name='Запуск пайплайна')),
            ],
            options={
                'verbose_name': 'Запуск узла',
                'verbose_name_plural': 'запуски узлов',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_port', models.CharField(default='main', help_text='Для узлов с несколькими выходами.', max_length=50, verbose_name='Порт источника')),
                ('target_port', models.CharField(default='main', help_text='Для узлов с несколькими входами (напр. JOIN: left/right).', max_length=50, verbose_name='Порт приёмника')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.node', verbose_name='Откуда')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.node', verbose_name='Куда')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.pipeline', verbose_name='Пайплайн')),
            ],
            options={
                'verbose_name': 'Ребро',
                'verbose_name_plural': 'рёбра',
                'constraints': [models.UniqueConstraint(fields=('pipeline', 'source_node', 'target_node', 'source_port', 'target_port'), name='unique_edge')],
            },
        ),
    ]
