# Generated by Django 6.0.2 on 2026-02-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noderun',
            name='logs',
        ),
    ]
