# Generated by Django 6.0.2 on 2026-03-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_noderun_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celery Task ID'),
        ),
    ]
