# Generated by Django 6.0.2 on 2026-03-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pipelinerun_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='columns_meta',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "col", "dtype": "int64"}, ...]', verbose_name='Метаданные столбцов'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='db_engine',
            field=models.CharField(blank=True, help_text='postgresql, mysql, ...', max_length=50, verbose_name='Движок БД'),
        ),
    ]
