# Generated by Django 6.0.2 on 2026-03-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_datasource_columns_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users/', verbose_name='Ссылка на аватар'),
        ),
    ]
