# Generated by Django 6.0.2 on 2026-04-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='db_engine',
            field=models.CharField(blank=True, help_text='postgresql, mysql, ...', max_length=255, verbose_name='Движок БД'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Celery Task ID'),
        ),
    ]
