# Generated by Django 6.0.2 on 2026-04-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_datasource_db_engine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['-created_at', 'pk'], 'verbose_name': 'Источник данных', 'verbose_name_plural': 'источники данных'},
        ),
        migrations.AlterModelOptions(
            name='edge',
            options={'ordering': ['pk'], 'verbose_name': 'Ребро', 'verbose_name_plural': 'рёбра'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['pk'], 'verbose_name': 'Узел', 'verbose_name_plural': 'узлы'},
        ),
        migrations.AlterModelOptions(
            name='noderun',
            options={'ordering': ['started_at', 'pk'], 'verbose_name': 'Запуск узла', 'verbose_name_plural': 'запуски узлов'},
        ),
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-created_at', 'pk'], 'verbose_name': 'Пайплайн', 'verbose_name_plural': 'пайплайны'},
        ),
        migrations.AlterModelOptions(
            name='pipelinerun',
            options={'ordering': ['-created_at', 'pk'], 'verbose_name': 'Запуск пайплайна', 'verbose_name_plural': 'запуски пайплайна'},
        ),
    ]
