# Generated by Django 6.0.2 on 2026-04-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_datasource_options_alter_edge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='run_mode',
            field=models.CharField(
                choices=[
                    ('full', 'Полный запуск'),
                    ('preview', 'Предпросмотр узла'),
                ],
                default='full',
                max_length=20,
                verbose_name='Режим запуска',
            ),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='target_node',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='targeted_runs',
                to='core.node',
                verbose_name='Целевой узел',
            ),
        ),
    ]
