# Generated by Django 6.0.2 on 2026-05-18 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='original_filename',
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('original_file', models.FileField(upload_to='uploads/originals/%Y/%m/', verbose_name='Оригинальный файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('sheets_metadata', models.JSONField(blank=True, default=list, help_text='[{"sheet_name": "Sheet1", "index": 0}, ...]', verbose_name='Метаданные листов')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Исходный файл',
                'verbose_name_plural': 'Исходные файлы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.sourcefile', verbose_name='Исходный файл'),
        ),
    ]
