# Generated by Django 6.0.2 on 2026-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_datasource_original_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='db_options',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры подключения (например, sslmode).', verbose_name='Опции подключения'),
        ),
    ]
